### ISSUE TITLE
No Windows support?

### ISSUE THREAD

**Issue by colinemondswieprecht** [anas-araid/vscode-supabase-cli#3]
After installing the extension on Windows, I noticed that it does not appear to run correctly. For example, if I press Ctrl+Shift+P and run "Run supabase db reset command", nothing happens and this error appears in the Extension Host logs:

```
2024-02-22 10:18:41.459 [error] Error: ENOENT: no such file or directory, lstat '/c:/Users/colin.emonds/Code/foo'
	at lstatSync (node:fs:1670:3)
	at Object.lstatSync (node:electron/js2c/asar_bundle:2:4026)
	at executeCommand (c:\Users\colin.emonds\.vscode\extensions\anasaraid.vscode-supabase-cli-0.0.1\out\utils\exec-command.js:9:40)
	at c:\Users\colin.emonds\.vscode\extensions\anasaraid.vscode-supabase-cli-0.0.1\out\register.js:28:160
	at Generator.next (<anonymous>)
	at c:\Users\colin.emonds\.vscode\extensions\anasaraid.vscode-supabase-cli-0.0.1\out\register.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\colin.emonds\.vscode\extensions\anasaraid.vscode-supabase-cli-0.0.1\out\register.js:4:12)
	at c:\Users\colin.emonds\.vscode\extensions\anasaraid.vscode-supabase-cli-0.0.1\out\register.js:28:72
	at s.h (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:175243)
	at s.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:176103)
	at d.S (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:147:5520)
        * snip many more lines *
``` 

The directory in the error message exists, but the path looks very odd. Is the leading slash intended?

**Comment by DuncanLHS** [comment]
Same issue here. Extension doesn't seem to connect to my DB properly and I get these error messages whenever I try running any command.
